module LanguageDetector

def detectLanguage
  lan = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
  language = 'English'
  
  case lan
  when 'sv'
    language = 'Swedish'
  when 'af'
    language = 'Afrikaans'
  when 'sq'
    language =  'Albanian'
  when 'eu'
    language =  'Basque'
  when 'bg'
    language = 'Bulgarian'
  when 'be'
    language = 'Byelorussian'
  when 'ca'
    language = 'Catalan'
  when 'zh'
    language = 'Chinese'
  when 'zh-cn'
    language = 'Chinese/China'
  when 'zh-tw'
    language = 'Chinese/Taiwan'
  when 'zh-hk'
    language = 'Chinese/Hong Kong'
  when 'zh-sg'
    language = 'Chinese/singapore'
  when 'hr'
    language = 'Croatian'
  when 'cs'
    language = 'Czech'
  when 'da'
    language = 'Danish'
  when 'nl'
    language = 'Dutch'
  when 'nl-be'
    language = 'Dutch/Belgium'
  when 'en'
    language = 'English'
  when 'en-gb'
    language = 'English'
  when 'en-us'
    language = 'English'
  when 'en-au'
    language = 'English'
  when 'en-ca'
    language = 'English'
  when 'en-nz'
    language = 'English'
  when 'en-ie'
    language = 'English'
  when 'en-za'
    language = 'English'
  when 'en-jm'
    language = 'English'
  when 'en-bz'
    language = 'English'
  when 'en-tt'
    language = 'English'
  when 'et'
    language = 'Estonian'
  when 'fo'
    language = 'Faeroese'
  when 'fa'
    language = 'Farsi'
  when 'fi'
    language = 'Finnish'
  when 'fr'
    language = 'French'
  when 'fr-be'
    language = 'French'
  when 'fr-fr'
    language = 'French'
  when 'fr-ch'
    language = 'French'
  when 'fr-ca'
    language = 'French'
  when 'fr-lu'
    language = 'French'
  when 'gd'
    language = 'Gaelic'
  when 'gl'
    language = 'Galician'
  when 'de'
    language = 'German'
  when 'de-at'
    language = 'German'
  when 'de-de'
    language = 'German'
  when 'de-ch'
    language = 'German'
  when 'de-lu'
    language = 'German'
  when 'de-li'
    language = 'German'
  when 'el'
    language = 'Greek'
  when 'hi'
    language = 'Hindi'
  when 'hu'
    language = 'Hungarian'
  when 'is'
    language = 'Icelandic'
  when 'id'
    language = 'Indonesian'
  when 'in'
    language = 'Indonesian'
  when 'ga'
    language = 'Irish'
  when 'it'
    language = 'Italian'
  when 'it-ch'
    language = 'Italian'
  when 'ja'
    language = 'Japanese'
  when 'ko'
    language = 'Korean'
  when 'lv'
    language = 'Latvian'
  when 'lt'
    language = 'Lithuanian'
  when 'mk'
    language = 'Macedonian'
  when 'ms'
    language = 'Malaysian'
  when 'mt'
    language = 'Maltese'
  when 'no'
    language = 'Norwegian'
  when 'pl'
    language = 'Polish'
  when 'pt'
    language = 'Portuguese'
  when 'pt-br'
    language = 'Portuguese'
  when 'rm'
    language = 'Rhaeto-Romanic'
  when 'ro'
    language = 'Romanian'
  when 'ro-mo'
    language = 'Romanian'
  when 'ru'
    language = 'Russian'
  when 'ru-mo'
    language = 'Russian'
  when 'gd'
    language = 'Scots Gaelic'
  when 'sr'
    language = 'Serbian'
  when 'sk'
    language = 'Slovack'
  when 'sl'
    language = 'Slovenian'
  when 'sb'
    language = 'Sorbian'
  when 'es'
    language = 'Spanish'
  when 'es-do'
    language = 'Spanish'
  when 'es-ar'
    language = 'Spanish'
  when 'es-co'
    language = 'Spanish'
  when 'es-mx'
    language = 'Spanish'
  when 'es-es'
    language = 'Spanish'
  when 'es-gt'
    language = 'Spanish'
  when 'es-cr'
    language = 'Spanish'
  when 'es-pa'
    language = 'Spanish'
  when 'es-ve'
    language = 'Spanish'
  when 'es-pe'
    language = 'Spanish'
  when 'es-ec'
    language = 'Spanish'
  when 'es-cl'
    language = 'Spanish'
  when 'es-uy'
    language = 'Spanish'
  when 'es-py'
    language = 'Spanish'
  when 'es-bo'
    language = 'Spanish'
  when 'es-sv'
    language = 'Spanish'
  when 'es-hn'
    language = 'Spanish'
  when 'es-ni'
    language = 'Spanish'
  when 'es-pr'
    language = 'Spanish'
  when 'sx'
    language = 'Sutu'
  when 'sv-fi'
    language = 'Swedish'
  when 'ts'
    language = 'Thai'
  when 'tn'
    language = 'Tswana'
  when 'tr'
    language = 'Turkish'
  when 'uk'
    language = 'Ukrainian'
  when 'ur'
    language = 'Urdu'
  when 'vi'
    language = 'Vietnamese'
  when 'xh'
    language = 'Xshosa'
  when 'ji'
    language = 'Yiddish'
  when 'zu'
    language = 'Zulu'   
  else
    language = 'English'
  end 
  return language
end

end